name: smartville
description: A new Flutter project.
publish_to: "none"
version: 1.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bulleted_list: ^0.0.1+0.1a
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.1
  firebase_core: ^1.10.2
  firebase_messaging: ^11.2.0
  flutter:
    sdk: flutter
  flutter_email_sender: ^5.0.2
  flutter_local_notifications: ^9.1.4
  flutter_pw_validator: ^1.3.0
  google_fonts: ^2.1.0
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  pin_code_fields: ^7.3.0
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  tutorial_coach_mark: ^1.2.1
  url_launcher: ^6.0.17

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/icons/launcher.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
